version: '3.3'

services:
  proxy:
    image: traefik
    networks:
      - gateway
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/traefik.toml
  dns:
    image: phensley/docker-dns
    command: --domain dev
    networks:
      - gateway
    ports:
      - "53:53"
    volumes:
      - /var/run/docker.sock:/docker.sock

networks:
  gateway:
    driver: bridge